# -*- coding: utf-8 -*-
"""Financial Market News Analysis.ipyn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G8ZPkOMlYcK514ROyap2z7pyLkugqhtB
"""

import pandas as pd
import numpy as np

data = pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Financial%20Market%20News.csv',encoding='ISO-8859-1')

data.shape

data.describe()

data.info()

data.columns

data.head()

data.tail()

news = []
for i in range(0,len(data.index)):
  news.append(" ".join(str(x) for x in data.iloc[i,2:27]))

news[1]

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase=True,ngram_range=(1,1))

news = cv.fit_transform(news)

X = news 
X.shape

y = data['Label']
y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=20)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=200)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_pred,y_test)
print(cm)

accuracy_score(y_pred,y_test)

print(classification_report(y_test,y_pred))

